name: Build and Test with Jest

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

env:
  PNPM_VERSION: 7.14.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2.5.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2.5.0

      - name: Run tests
        run: npm run test

  compare-test-coverage:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2.5.0

      - name: Compare test coverage
        run: ArtiomTr/jest-coverage-report-action@v2
